### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by dpopov**

### CODE REVIEW

**Comment by ezefranca** [comment]
@drichardson please accept this PR

**Comment by drichardson** [comment]
Hi @ezefranca, would be happy to accept, but first could you tell me the reason for the change and what it accomplishes?

**Comment by drichardson** [comment]
Oh actually, I see it was originally submitted by @dpopov. @dpopov could you please tell me the reason for the change and presuming it makes sense I'll merge it asap.

**Comment by drichardson** [comment]
Oh, derp. I see the title says it all (Swift 3). I'll try to build and will merge if it works.

**Comment by drichardson** [comment]
Just tried building @dpopov's branch but getting some Swift errors and the Xcode Swift 3 convert tool is asking me to make changes that will break cocoapod users, so I need to spend a few minutes to look at this. Will try to get to it later today.

**Comment by drichardson** [comment]
This code doesn't work, I'm going to have to revert it. The indexes in the loop are incorrect.

**Comment by dpopov** [comment]
I completely missed this whole conversation. My apologies! What was the problem with the loop?

**Comment by drichardson** [comment]
I have a terrible memory and this was two weeks ago ;) but I think it was an index out of bounds exception when running the unit tests.

**Pull request merged**
